function Hd = comb_filt
%COMB_FILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 19-Sep-2023 17:55:15

% IIR Comb Notching filter designed using the IIRCOMB function.

% All frequency values are in Hz.
Fs = 500;  % Sampling Frequency

N     = 10;  % Order
BW    = 5;   % Bandwidth
Apass = 1;   % Bandwidth Attenuation

[b, a] = iircomb(N, BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
